"""GitHub review publisher: Formats and publishes triage findings to GitHub."""

import logging
import uuid
from typing import Any

from prism.config import get_settings
from prism.github.client import GitHubClient, GitHubClientProtocol
from prism.services.models import PublishedReviewRecord, ReviewRecord
from prism.storage.review_store import ReviewStore

logger = logging.getLogger(__name__)


def format_summary_comment(review: ReviewRecord) -> str:
    """Format structured PRism triage findings into a markdown summary comment."""
    status_display = review.status.value.replace("_", " ").title()
    risk_display = review.risk_level.upper()

    # Risk badge formatting
    risk_emoji = {
        "CRITICAL": "🚨",
        "HIGH": "⚠️",
        "MEDIUM": "🟡",
        "LOW": "✅",
    }.get(risk_display, "ℹ️")

    lines = [
        f"## {risk_emoji} PRism Automated Review & Triage",
        "",
        f"**Risk Level:** `{risk_display}` | **Status:** `{status_display}`",
        "",
    ]

    # Human approval status
    if review.approval_status:
        lines.append(f"**Human Gate Decision:** `{review.approval_status}`")
        if review.reviewer_notes:
            lines.append(f"> *Reviewer Note:* {review.reviewer_notes}")
        lines.append("")

    # Prompt injection guardrail alert if flagged
    if review.injection_detected:
        lines.extend([
            "> [!CAUTION]",
            "> **Prompt Injection Guardrail Triggered:**",
            "> Suspicious instruction patterns were detected in this Pull Request's content.",
            "> Content was quarantined and evaluated as untrusted repository data.",
            "",
        ])

    # Executive summary
    if review.summary:
        lines.extend([
            "### Summary",
            review.summary,
            "",
        ])

    # Severity counts
    lines.extend([
        "### Findings Breakdown",
        f"- **Critical:** {review.critical_count}",
        f"- **High:** {review.high_count}",
        f"- **Medium:** {review.medium_count}",
        f"- **Low:** {review.low_count}",
        f"- **Total Identified:** {review.findings_count}",
        "",
    ])

    # Policy reasons
    if review.policy_reasons:
        lines.extend([
            "### Policy Evaluation",
            "The following deterministic rules triggered elevated review:",
        ])
        for r in review.policy_reasons:
            lines.append(f"- {r}")
        lines.append("")

    # Highlighted key findings (critical and high)
    significant_findings = [
        f for f in review.raw_findings
        if f.get("severity", "").lower() in ("critical", "high")
    ]
    if significant_findings:
        lines.extend([
            "### Critical & High Priority Issues",
            "",
        ])
        for f in significant_findings[:10]:
            sev = f.get("severity", "high").upper()
            title = f.get("title", "Finding")
            file_loc = f"{f.get('file')}:{f.get('line')}" if f.get("line") else f.get("file", "general")
            desc = f.get("description", "")
            rec = f.get("recommendation", "")

            lines.extend([
                f"#### `[{sev}]` {title} (`{file_loc}`)",
                f"{desc}",
                f"**Recommendation:** {rec}",
                "",
            ])

    lines.extend([
        "---",
        "*Review generated by PRism — Agentic GitHub PR Review & Triage System.*",
    ])

    return "\n".join(lines)


def format_inline_comment(finding: dict[str, Any]) -> str:
    """Format an individual finding for an inline diff comment."""
    sev = finding.get("severity", "medium").upper()
    title = finding.get("title", "Review Finding")
    desc = finding.get("description", "")
    rec = finding.get("recommendation", "")

    lines = [
        f"**PRism [{sev}]**: **{title}**",
        "",
        desc,
    ]
    if rec:
        lines.extend([
            "",
            f"**Recommendation:** {rec}",
        ])
    return "\n".join(lines)


class ReviewPublisher:
    """Publishes PRism review summaries and inline comments to GitHub."""

    def __init__(
        self,
        github_client: GitHubClientProtocol | None = None,
        store: ReviewStore | None = None,
    ):
        self.github_client = github_client or GitHubClient()
        self.store = store or ReviewStore()

    async def publish_review(
        self,
        review: ReviewRecord,
        publish_inline: bool | None = None,
    ) -> PublishedReviewRecord:
        """Publish review results to GitHub, guarding against duplicate publications."""
        owner, repo = get_settings().parse_repo_slug(review.repository)
        pull_number = review.pull_number
        head_sha = review.head_sha

        # 1. Check for duplicate publication on the exact same commit
        existing_pub = await self.store.get_publication_for_commit(
            repository=review.repository,
            pull_number=pull_number,
            head_sha=head_sha,
        )
        if existing_pub:
            logger.info(
                "Review already published for %s#%s@%s (pub ID: %s). Skipping duplicate.",
                review.repository,
                pull_number,
                head_sha,
                existing_pub.publication_id,
            )
            return existing_pub

        logger.info(
            "Publishing review for %s#%s@%s (risk: %s)",
            review.repository,
            pull_number,
            head_sha,
            review.risk_level,
        )

        # 2. Post PR-level summary comment
        summary_body = format_summary_comment(review)
        summary_result = await self.github_client.post_review_comment(
            owner=owner,
            repo=repo,
            pull_number=pull_number,
            body=summary_body,
        )
        summary_comment_id = summary_result.id

        # 3. Post inline review comments if configured
        inline_count = 0
        should_inline = (
            publish_inline
            if publish_inline is not None
            else get_settings().publish_inline_comments
        )

        if should_inline:
            actionable_findings = [
                f for f in review.raw_findings
                if f.get("file") and f.get("line") is not None
            ]
            for finding in actionable_findings[:15]:  # Safety cap on comment flood
                try:
                    inline_body = format_inline_comment(finding)
                    await self.github_client.post_review_comment(
                        owner=owner,
                        repo=repo,
                        pull_number=pull_number,
                        body=inline_body,
                        commit_id=head_sha,
                        path=finding["file"],
                        line=finding["line"],
                    )
                    inline_count += 1
                except Exception as exc:  # noqa: BLE001
                    logger.warning(
                        "Failed to post inline comment for %s:%s: %s",
                        finding.get("file"),
                        finding.get("line"),
                        exc,
                    )

        # 4. Record publication in store
        pub_record = PublishedReviewRecord(
            publication_id=str(uuid.uuid4()),
            review_id=review.review_id,
            repository=review.repository,
            pull_number=pull_number,
            head_sha=head_sha,
            summary_comment_id=summary_comment_id,
            inline_comments_count=inline_count,
        )
        await self.store.record_publication(pub_record)

        # Update review record with publication reference
        review.publication_id = pub_record.publication_id
        await self.store.save_review(review)

        logger.info(
            "Successfully published review %s for %s#%s (summary ID: %s, inline comments: %d)",
            review.review_id,
            review.repository,
            pull_number,
            summary_comment_id,
            inline_count,
        )
        return pub_record
